import { createAction, createAsyncAction } from "typesafe-actions"
import { Company, Unit, CREATECOMPANYCRED, UPDATECOMPANYCRED, CREATEUNITCRED, UPDATEUNITCRED, CREATEENTITYCRED, UPDATEENTITYCRED, Entity } from "../interface/companyInterface";

const SELECT_INDEX = "SELECT_INDEX"
export const selectIndexAction = createAction(SELECT_INDEX,
    action => {
        return (index: number) => action(index)
    })

const SELECT_COMPANY = "SELECT_COMPANY"
export const selectCompanyAction = createAction(SELECT_COMPANY,
    action => {
        return (company: Company) => action(company)
    })

const SELECT_UPDATE_COMPANY = "SELECT_UPDATE_COMPANY"
export const selectUpdateCompanyAction = createAction(SELECT_UPDATE_COMPANY,
    action => {
        return (company: Company) => action(company)
    })

const SELECT_UPDATE_ENTITY = "SELECT_UPDATE_ENTITY"
export const selectUpdateEntityAction = createAction(SELECT_UPDATE_ENTITY,
    action => {
        return (entity: Entity) => action(entity)
    })

const SELECT_UNIT = "SELECT_UNIT"
export const selectUnitAction = createAction(SELECT_UNIT,
    action => {
        return (unit: Unit) => action(unit)
    })

const SELECT_SUBUNIT = "SELECT_SUBUNIT"
export const selectSubUnitAction = createAction(SELECT_SUBUNIT,
    action => {
        return (unit: Unit) => action(unit)
    })

const SELECT_UPDATE_UNIT = "SELECT_UPDATE_UNIT"
export const selectUpdateUnitAction = createAction(SELECT_UPDATE_UNIT,
    action => {
        return (unit: Unit) => action(unit)
    })

const GET_COMPANY_LIST_REQUEST = "GET_COMPANY_LIST_REQUEST"
const GET_COMPANY_LIST_SUCCESS = "GET_COMPANY_LIST_SUCCESS"
const GET_COMPANY_LIST_FAILURE = "GET_COMPANY_LIST_FAILURE"
export const getCompanyListAction = createAsyncAction(
    GET_COMPANY_LIST_REQUEST,
    GET_COMPANY_LIST_SUCCESS,
    GET_COMPANY_LIST_FAILURE
)<void, Company[], void>()

const GET_CHILD_COMPANY_LIST_REQUEST = "GET_CHILD_COMPANY_LIST_REQUEST"
const GET_CHILD_COMPANY_LIST_SUCCESS = "GET_CHILD_COMPANY_LIST_SUCCESS"
const GET_CHILD_COMPANY_LIST_FAILURE = "GET_CHILD_COMPANY_LIST_FAILURE"
export const getChildCompanyListAction = createAsyncAction(
    GET_CHILD_COMPANY_LIST_REQUEST,
    GET_CHILD_COMPANY_LIST_SUCCESS,
    GET_CHILD_COMPANY_LIST_FAILURE
)<void, Company[], void>()


const CREATE_COMPANY_REQUEST = "CREATE_COMPANY_REQUEST"
const CREATE_COMPANY_SUCCESS = "CREATE_COMPANY_SUCCESS"
const CREATE_COMPANY_FAILURE = "CREATE_COMPANY_FAILURE"
export const createCompanyAction = createAsyncAction(
    CREATE_COMPANY_REQUEST,
    CREATE_COMPANY_SUCCESS,
    CREATE_COMPANY_FAILURE
)<CREATECOMPANYCRED, void, void>()

const CREATE_ENTITY_REQUEST = "CREATE_ENTITY_REQUEST"
const CREATE_ENTITY_SUCCESS = "CREATE_ENTITY_SUCCESS"
const CREATE_ENTITY_FAILURE = "CREATE_ENTITY_FAILURE"
export const createEntityAction = createAsyncAction(
    CREATE_ENTITY_REQUEST,
    CREATE_ENTITY_SUCCESS,
    CREATE_ENTITY_FAILURE
)<CREATEENTITYCRED, void, void>()

const UPDATE_COMPANY_REQUEST = "UPDATE_COMPANY_REQUEST"
const UPDATE_COMPANY_SUCCESS = "UPDATE_COMPANY_SUCCESS"
const UPDATE_COMPANY_FAILURE = "UPDATE_COMPANY_FAILURE"
export const updateCompanyAction = createAsyncAction(
    UPDATE_COMPANY_REQUEST,
    UPDATE_COMPANY_SUCCESS,
    UPDATE_COMPANY_FAILURE
)<UPDATECOMPANYCRED, void, void>()

const UPDATE_ENTITY_REQUEST = "UPDATE_ENTITY_REQUEST"
const UPDATE_ENTITY_SUCCESS = "UPDATE_ENTITY_SUCCESS"
const UPDATE_ENTITY_FAILURE = "UPDATE_ENTITY_FAILURE"
export const updateEntityAction = createAsyncAction(
    UPDATE_ENTITY_REQUEST,
    UPDATE_ENTITY_SUCCESS,
    UPDATE_ENTITY_FAILURE
)<UPDATEENTITYCRED, void, void>()

const DELETE_COMPANY_REQUEST = "DELETE_COMPANY_REQUEST"
const DELETE_COMPANY_SUCCESS = "DELETE_COMPANY_SUCCESS"
const DELETE_COMPANY_FAILURE = "DELETE_COMPANY_FAILURE"
export const deleteCompanyAction = createAsyncAction(
    DELETE_COMPANY_REQUEST,
    DELETE_COMPANY_SUCCESS,
    DELETE_COMPANY_FAILURE
)<string, void, void>()

const DELETE_ENTITY_REQUEST = "DELETE_ENTITY_REQUEST"
const DELETE_ENTITY_SUCCESS = "DELETE_ENTITY_SUCCESS"
const DELETE_ENTITY_FAILURE = "DELETE_ENTITY_FAILURE"
export const deleteEntityAction = createAsyncAction(
    DELETE_ENTITY_REQUEST,
    DELETE_ENTITY_SUCCESS,
    DELETE_ENTITY_FAILURE
)<string, void, void>()

const GET_DIVISION_LIST_REQUEST = "GET_DIVISION_LIST_REQUEST"
const GET_DIVISION_LIST_SUCCESS = "GET_DIVISION_LIST_SUCCESS"
const GET_DIVISION_LIST_FAILURE = "GET_DIVISION_LIST_FAILURE"
export const getDivisionListAction = createAsyncAction(
    GET_DIVISION_LIST_REQUEST,
    GET_DIVISION_LIST_SUCCESS,
    GET_DIVISION_LIST_FAILURE
)<void, Unit[], void>()

const GET_UNIT_LIST_REQUEST = "GET_UNIT_LIST_REQUEST"
const GET_UNIT_LIST_SUCCESS = "GET_UNIT_LIST_SUCCESS"
const GET_UNIT_LIST_FAILURE = "GET_UNIT_LIST_FAILURE"
export const getUnitListAction = createAsyncAction(
    GET_UNIT_LIST_REQUEST,
    GET_UNIT_LIST_SUCCESS,
    GET_UNIT_LIST_FAILURE
)<void, Unit[], void>()

const GET_SUBUNIT_LIST_REQUEST = "GET_SUBUNIT_LIST_REQUEST"
const GET_SUBUNIT_LIST_SUCCESS = "GET_SUBUNIT_LIST_SUCCESS"
const GET_SUBUNIT_LIST_FAILURE = "GET_SUBUNIT_LIST_FAILURE"
export const getSubUnitListAction = createAsyncAction(
    GET_SUBUNIT_LIST_REQUEST,
    GET_SUBUNIT_LIST_SUCCESS,
    GET_SUBUNIT_LIST_FAILURE
)<void, Unit[], void>()

const GET_CHILD_UNIT_LIST_REQUEST = "GET_CHILD_UNIT_LIST_REQUEST"
const GET_CHILD_UNIT_LIST_SUCCESS = "GET_CHILD_UNIT_LIST_SUCCESS"
const GET_CHILD_UNIT_LIST_FAILURE = "GET_CHILD_UNIT_LIST_FAILURE"
export const getChildUnitListAction = createAsyncAction(
    GET_CHILD_UNIT_LIST_REQUEST,
    GET_CHILD_UNIT_LIST_SUCCESS,
    GET_CHILD_UNIT_LIST_FAILURE
)<void, Unit[], void>()

const CREATE_UNIT_REQUEST = "CREATE_UNIT_REQUEST"
const CREATE_UNIT_SUCCESS = "CREATE_UNIT_SUCCESS"
const CREATE_UNIT_FAILURE = "CREATE_UNIT_FAILURE"
export const createUnitAction = createAsyncAction(
    CREATE_UNIT_REQUEST,
    CREATE_UNIT_SUCCESS,
    CREATE_UNIT_FAILURE
)<CREATEUNITCRED, void, void>()

const CREATE_SUBUNIT_REQUEST = "CREATE_SUBUNIT_REQUEST"
const CREATE_SUBUNIT_SUCCESS = "CREATE_SUBUNIT_SUCCESS"
const CREATE_SUBUNIT_FAILURE = "CREATE_SUBUNIT_FAILURE"
export const createSubUnitAction = createAsyncAction(
    CREATE_SUBUNIT_REQUEST,
    CREATE_SUBUNIT_SUCCESS,
    CREATE_SUBUNIT_FAILURE
)<CREATEUNITCRED, void, void>()

const CREATE_CHILDUNIT_REQUEST = "CREATE_CHILDUNIT_REQUEST"
const CREATE_CHILDUNIT_SUCCESS = "CREATE_CHILDUNIT_SUCCESS"
const CREATE_CHILDUNIT_FAILURE = "CREATE_CHILDUNIT_FAILURE"
export const createChildUnitAction = createAsyncAction(
    CREATE_CHILDUNIT_REQUEST,
    CREATE_CHILDUNIT_SUCCESS,
    CREATE_CHILDUNIT_FAILURE
)<CREATEUNITCRED, void, void>()

const UPDATE_UNIT_REQUEST = "UPDATE_UNIT_REQUEST"
const UPDATE_UNIT_SUCCESS = "UPDATE_UNIT_SUCCESS"
const UPDATE_UNIT_FAILURE = "UPDATE_UNIT_FAILURE"
export const updateUnitAction = createAsyncAction(
    UPDATE_UNIT_REQUEST,
    UPDATE_UNIT_SUCCESS,
    UPDATE_UNIT_FAILURE
)<UPDATEUNITCRED, void, void>()

const DELETE_UNIT_REQUEST = "DELETE_UNIT_REQUEST"
const DELETE_UNIT_SUCCESS = "DELETE_UNIT_SUCCESS"
const DELETE_UNIT_FAILURE = "DELETE_UNIT_FAILURE"
export const deleteUnitAction = createAsyncAction(
    DELETE_UNIT_REQUEST,
    DELETE_UNIT_SUCCESS,
    DELETE_UNIT_FAILURE
)<string, void, void>()

const UPDATE_SUBUNIT_REQUEST = "UPDATE_SUBUNIT_REQUEST"
const UPDATE_SUBUNIT_SUCCESS = "UPDATE_SUBUNIT_SUCCESS"
const UPDATE_SUBUNIT_FAILURE = "UPDATE_SUBUNIT_FAILURE"
export const updateSubUnitAction = createAsyncAction(
    UPDATE_SUBUNIT_REQUEST,
    UPDATE_SUBUNIT_SUCCESS,
    UPDATE_SUBUNIT_FAILURE
)<UPDATEUNITCRED, void, void>()

const DELETE_SUBUNIT_REQUEST = "DELETE_SUBUNIT_REQUEST"
const DELETE_SUBUNIT_SUCCESS = "DELETE_SUBUNIT_SUCCESS"
const DELETE_SUBUNIT_FAILURE = "DELETE_SUBUNIT_FAILURE"
export const deleteSubUnitAction = createAsyncAction(
    DELETE_SUBUNIT_REQUEST,
    DELETE_SUBUNIT_SUCCESS,
    DELETE_SUBUNIT_FAILURE
)<string, void, void>()

const UPDATE_CHILDUNIT_REQUEST = "UPDATE_CHILDUNIT_REQUEST"
const UPDATE_CHILDUNIT_SUCCESS = "UPDATE_CHILDUNIT_SUCCESS"
const UPDATE_CHILDUNIT_FAILURE = "UPDATE_CHILDUNIT_FAILURE"
export const updateChildUnitAction = createAsyncAction(
    UPDATE_CHILDUNIT_REQUEST,
    UPDATE_CHILDUNIT_SUCCESS,
    UPDATE_CHILDUNIT_FAILURE
)<UPDATEUNITCRED, void, void>()

const DELETE_CHILDUNIT_REQUEST = "DELETE_CHILDUNIT_REQUEST"
const DELETE_CHILDUNIT_SUCCESS = "DELETE_CHILDUNIT_SUCCESS"
const DELETE_CHILDUNIT_FAILURE = "DELETE_CHILDUNIT_FAILURE"
export const deleteChildUnitAction = createAsyncAction(
    DELETE_CHILDUNIT_REQUEST,
    DELETE_CHILDUNIT_SUCCESS,
    DELETE_CHILDUNIT_FAILURE
)<string, void, void>()

const GET_COMPANY_BY_COUNTRY_REQUEST = "GET_COMPANY_BY_COUNTRY_REQUEST"
const GET_COMPANY_BY_COUNTRY_SUCCESS = "GET_COMPANY_BY_COUNTRY_SUCCESS"
const GET_COMPANY_BY_COUNTRY_FAILURE = "GET_COMPANY_BY_COUNTRY_FAILURE"
export const getCompanyByCountryAction = createAsyncAction(
    GET_COMPANY_BY_COUNTRY_REQUEST,
    GET_COMPANY_BY_COUNTRY_SUCCESS,
    GET_COMPANY_BY_COUNTRY_FAILURE
)<string, any[], void>()

const GET_COMPANY_BY_REGION_REQUEST = "GET_COMPANY_BY_REGION_REQUEST"
const GET_COMPANY_BY_REGION_SUCCESS = "GET_COMPANY_BY_REGION_SUCCESS"
const GET_COMPANY_BY_REGION_FAILURE = "GET_COMPANY_BY_REGION_FAILURE"
export const getCompanyByRegionAction = createAsyncAction(
    GET_COMPANY_BY_REGION_REQUEST,
    GET_COMPANY_BY_REGION_SUCCESS,
    GET_COMPANY_BY_REGION_FAILURE
)<string, any[], void>()