import { createAsyncAction, createAction } from "typesafe-actions";
import { JobGrade, CREATEJOBGRADECRED, UPDATEJOBGRADECRED } from "../interface/jobgradeInterface";

const SELECT_JOBGRADE = "SELECT_JOBGRADE"
export const selectJobGradeAction = createAction(SELECT_JOBGRADE,
    action => {
        return (jobgrade: JobGrade) => action(jobgrade)
    })

const GET_JOBGRADE_LIST_REQUEST = "GET_JOBGRADE_LIST_REQUEST"
const GET_JOBGRADE_LIST_SUCCESS = "GET_JOBGRADE_LIST_SUCCESS"
const GET_JOBGRADE_LIST_FAILURE = "GET_JOBGRADE_LIST_FAILURE"
export const getJobGradeListAction = createAsyncAction(
    GET_JOBGRADE_LIST_REQUEST,
    GET_JOBGRADE_LIST_SUCCESS,
    GET_JOBGRADE_LIST_FAILURE
)<void, JobGrade[], void>()

const CREATE_JOBGRADE_REQUEST = "CREATE_JOBGRADE_REQUEST"
const CREATE_JOBGRADE_SUCCESS = "CREATE_JOBGRADE_SUCCESS"
const CREATE_JOBGRADE_FAILURE = "CREATE_JOBGRADE_FAILURE"
export const createJobGradeAction = createAsyncAction(
    CREATE_JOBGRADE_REQUEST,
    CREATE_JOBGRADE_SUCCESS,
    CREATE_JOBGRADE_FAILURE
)<CREATEJOBGRADECRED, void, void>()

const UPDATE_JOBGRADE_REQUEST = "UPDATE_JOBGRADE_REQUEST"
const UPDATE_JOBGRADE_SUCCESS = "UPDATE_JOBGRADE_SUCCESS"
const UPDATE_JOBGRADE_FAILURE = "UPDATE_JOBGRADE_FAILURE"
export const updateJobGradeAction = createAsyncAction(
    UPDATE_JOBGRADE_REQUEST,
    UPDATE_JOBGRADE_SUCCESS,
    UPDATE_JOBGRADE_FAILURE
)<UPDATEJOBGRADECRED, void, void>()

const DELETE_JOBGRADE_REQUEST = "DELETE_JOBGRADE_REQUEST"
const DELETE_JOBGRADE_SUCCESS = "DELETE_JOBGRADE_SUCCESS"
const DELETE_JOBGRADE_FAILURE = "DELETE_JOBGRADE_FAILURE"
export const deleteJobGradeAction = createAsyncAction(
    DELETE_JOBGRADE_REQUEST,
    DELETE_JOBGRADE_SUCCESS,
    DELETE_JOBGRADE_FAILURE
)<string, void, void>()