import { createAsyncAction, createAction } from "typesafe-actions";
import { JobPosition, CREATEJOBPOSITIONCRED, UPDATEJOBPOSITIONCRED } from "../interface/jobpositionInterface";

const SELECT_JOBPOSITION = "SELECT_JOBPOSITION"
export const selectJobPositionAction = createAction(SELECT_JOBPOSITION,
    action => {
        return (jobposition: JobPosition) => action(jobposition)
    })

const GET_JOBPOSITION_LIST_REQUEST = "GET_JOBPOSITION_LIST_REQUEST"
const GET_JOBPOSITION_LIST_SUCCESS = "GET_JOBPOSITION_LIST_SUCCESS"
const GET_JOBPOSITION_LIST_FAILURE = "GET_JOBPOSITION_LIST_FAILURE"
export const getJobPositionListAction = createAsyncAction(
    GET_JOBPOSITION_LIST_REQUEST,
    GET_JOBPOSITION_LIST_SUCCESS,
    GET_JOBPOSITION_LIST_FAILURE
)<void, JobPosition[], void>()

const CREATE_JOBPOSITION_REQUEST = "CREATE_JOBPOSITION_REQUEST"
const CREATE_JOBPOSITION_SUCCESS = "CREATE_JOBPOSITION_SUCCESS"
const CREATE_JOBPOSITION_FAILURE = "CREATE_JOBPOSITION_FAILURE"
export const createJobPositionAction = createAsyncAction(
    CREATE_JOBPOSITION_REQUEST,
    CREATE_JOBPOSITION_SUCCESS,
    CREATE_JOBPOSITION_FAILURE
)<CREATEJOBPOSITIONCRED, void, void>()

const UPDATE_JOBPOSITION_REQUEST = "UPDATE_JOBPOSITION_REQUEST"
const UPDATE_JOBPOSITION_SUCCESS = "UPDATE_JOBPOSITION_SUCCESS"
const UPDATE_JOBPOSITION_FAILURE = "UPDATE_JOBPOSITION_FAILURE"
export const updateJobPositionAction = createAsyncAction(
    UPDATE_JOBPOSITION_REQUEST,
    UPDATE_JOBPOSITION_SUCCESS,
    UPDATE_JOBPOSITION_FAILURE
)<UPDATEJOBPOSITIONCRED, void, void>()

const DELETE_JOBPOSITION_REQUEST = "DELETE_JOBPOSITION_REQUEST"
const DELETE_JOBPOSITION_SUCCESS = "DELETE_JOBPOSITION_SUCCESS"
const DELETE_JOBPOSITION_FAILURE = "DELETE_JOBPOSITION_FAILURE"
export const deleteJobPositionAction = createAsyncAction(
    DELETE_JOBPOSITION_REQUEST,
    DELETE_JOBPOSITION_SUCCESS,
    DELETE_JOBPOSITION_FAILURE
)<string, void, void>()
