import { createAsyncAction, createAction } from "typesafe-actions";
import { OfferModel, CREATEOFFERMODELCRED , UPDATEOFFERMODELCRED } from "../interface/offerModelInterface";

const SELECT_OFFERMODEL = "SELECT_OFFERMODEL"
export const selectOfferModelAction = createAction(SELECT_OFFERMODEL,
    action => {
        return (offermodel: OfferModel) => action(offermodel)
    })

const GET_OFFERMODEL_LIST_REQUEST = "GET_OFFERMODEL_LIST_REQUEST"
const GET_OFFERMODEL_LIST_SUCCESS = "GET_OFFERMODEL_LIST_SUCCESS"
const GET_OFFERMODEL_LIST_FAILURE = "GET_OFFERMODEL_LIST_FAILURE"
export const getOfferModelListAction = createAsyncAction(
    GET_OFFERMODEL_LIST_REQUEST,
    GET_OFFERMODEL_LIST_SUCCESS,
    GET_OFFERMODEL_LIST_FAILURE
)<void, OfferModel[], void>()

const CREATE_OFFERMODEL_REQUEST = "CREATE_OFFERMODEL_REQUEST"
const CREATE_OFFERMODEL_SUCCESS = "CREATE_OFFERMODEL_SUCCESS"
const CREATE_OFFERMODEL_FAILURE = "CREATE_OFFERMODEL_FAILURE"
export const createOfferModelAction = createAsyncAction(
    CREATE_OFFERMODEL_REQUEST,
    CREATE_OFFERMODEL_SUCCESS,
    CREATE_OFFERMODEL_FAILURE
)<CREATEOFFERMODELCRED, void, void>()

const UPDATE_OFFERMODEL_REQUEST = "UPDATE_OFFERMODEL_REQUEST"
const UPDATE_OFFERMODEL_SUCCESS = "UPDATE_OFFERMODEL_SUCCESS"
const UPDATE_OFFERMODEL_FAILURE = "UPDATE_OFFERMODEL_FAILURE"
export const updateOfferModelAction = createAsyncAction(
    UPDATE_OFFERMODEL_REQUEST,
    UPDATE_OFFERMODEL_SUCCESS,
    UPDATE_OFFERMODEL_FAILURE
)<UPDATEOFFERMODELCRED, void, void>()

const DELETE_OFFERMODEL_REQUEST = "DELETE_OFFERMODEL_REQUEST"
const DELETE_OFFERMODEL_SUCCESS = "DELETE_OFFERMODEL_SUCCESS"
const DELETE_OFFERMODEL_FAILURE = "DELETE_OFFERMODEL_FAILURE"
export const deleteOfferModelAction = createAsyncAction(
    DELETE_OFFERMODEL_REQUEST,
    DELETE_OFFERMODEL_SUCCESS,
    DELETE_OFFERMODEL_FAILURE
)<string, void, void>()
