import { createAsyncAction, createAction } from "typesafe-actions";
import { SalaryRange, CREATESALARYRANGECRED, UPDATESALARYRANGECRED } from "../interface/salaryRangeInterface";

const SELECT_SALARYRANGE = "SELECT_SALARYRANGE"
export const selectSalaryRangeAction = createAction(SELECT_SALARYRANGE,
    action => {
        return (salaryrange: SalaryRange) => action(salaryrange)
    })

const GET_SALARYRANGE_LIST_REQUEST = "GET_SALARYRANGE_LIST_REQUEST"
const GET_SALARYRANGE_LIST_SUCCESS = "GET_SALARYRANGE_LIST_SUCCESS"
const GET_SALARYRANGE_LIST_FAILURE = "GET_SALARYRANGE_LIST_FAILURE"
export const getSalaryRangeListAction = createAsyncAction(
    GET_SALARYRANGE_LIST_REQUEST,
    GET_SALARYRANGE_LIST_SUCCESS,
    GET_SALARYRANGE_LIST_FAILURE
)<void, SalaryRange[], void>()

const CREATE_SALARYRANGE_REQUEST = "CREATE_SALARYRANGE_REQUEST"
const CREATE_SALARYRANGE_SUCCESS = "CREATE_SALARYRANGE_SUCCESS"
const CREATE_SALARYRANGE_FAILURE = "CREATE_SALARYRANGE_FAILURE"
export const createSalaryRangeAction = createAsyncAction(
    CREATE_SALARYRANGE_REQUEST,
    CREATE_SALARYRANGE_SUCCESS,
    CREATE_SALARYRANGE_FAILURE
)<CREATESALARYRANGECRED, void, void>()

const UPDATE_SALARYRANGE_REQUEST = "UPDATE_SALARYRANGE_REQUEST"
const UPDATE_SALARYRANGE_SUCCESS = "UPDATE_SALARYRANGE_SUCCESS"
const UPDATE_SALARYRANGE_FAILURE = "UPDATE_SALARYRANGE_FAILURE"
export const updateSalaryRangeAction = createAsyncAction(
    UPDATE_SALARYRANGE_REQUEST,
    UPDATE_SALARYRANGE_SUCCESS,
    UPDATE_SALARYRANGE_FAILURE
)<UPDATESALARYRANGECRED, void, void>()

const DELETE_SALARYRANGE_REQUEST = "DELETE_SALARYRANGE_REQUEST"
const DELETE_SALARYRANGE_SUCCESS = "DELETE_SALARYRANGE_SUCCESS"
const DELETE_SALARYRANGE_FAILURE = "DELETE_SALARYRANGE_FAILURE"
export const deleteSalaryRangeAction = createAsyncAction(
    DELETE_SALARYRANGE_REQUEST,
    DELETE_SALARYRANGE_SUCCESS,
    DELETE_SALARYRANGE_FAILURE
)<string, void, void>()