import { createAction, createAsyncAction } from "typesafe-actions"
import { Sector, CREATESECTORCRED, UPDATESECTORCRED, CREATEINDUSTRYCRED, UPDATEINDUSTRYCRED } from "../interface/sectorInterface";

interface GETSECTORLISTCRED {
    session_key: string
}

const SELECT_SECTOR = "SELECT_SECTOR"
export const selectSectorAction = createAction(SELECT_SECTOR,
    action => {
        return (jf: Sector) => action(jf)
    })

const GET_SECTOR_LIST_REQUEST = "GET_SECTOR_LIST_REQUEST"
const GET_SECTOR_LIST_SUCCESS = "GET_SECTOR_LIST_SUCCESS"
const GET_SECTOR_LIST_FAILURE = "GET_SECTOR_LIST_FAILURE"
export const getSectorListAction = createAsyncAction(
    GET_SECTOR_LIST_REQUEST,
    GET_SECTOR_LIST_SUCCESS,
    GET_SECTOR_LIST_FAILURE
)<void, Sector[], void>()

const CREATE_SECTOR_REQUEST = "CREATE_SECTOR_REQUEST"
const CREATE_SECTOR_SUCCESS = "CREATE_SECTOR_SUCCESS"
const CREATE_SECTOR_FAILURE = "CREATE_SECTOR_FAILURE"
export const createSectorAction = createAsyncAction(
    CREATE_SECTOR_REQUEST,
    CREATE_SECTOR_SUCCESS,
    CREATE_SECTOR_FAILURE
)<CREATESECTORCRED, void, void>()

const UPDATE_SECTOR_REQUEST = "UPDATE_SECTOR_REQUEST"
const UPDATE_SECTOR_SUCCESS = "UPDATE_SECTOR_SUCCESS"
const UPDATE_SECTOR_FAILURE = "UPDATE_SECTOR_FAILURE"
export const updateSectorAction = createAsyncAction(
    UPDATE_SECTOR_REQUEST,
    UPDATE_SECTOR_SUCCESS,
    UPDATE_SECTOR_FAILURE
)<UPDATESECTORCRED, void, void>()


const DELETE_SECTOR_REQUEST = "DELETE_SECTOR_REQUEST"
const DELETE_SECTOR_SUCCESS = "DELETE_SECTOR_SUCCESS"
const DELETE_SECTOR_FAILURE = "DELETE_SECTOR_FAILURE"
export const deleteSectorAction = createAsyncAction(
    DELETE_SECTOR_REQUEST,
    DELETE_SECTOR_SUCCESS,
    DELETE_SECTOR_FAILURE
)<string, string, void>()


const CREATE_INDUSTRY_REQUEST = "CREATE_INDUSTRY_REQUEST"
const CREATE_INDUSTRY_SUCCESS = "CREATE_INDUSTRY_SUCCESS"
const CREATE_INDUSTRY_FAILURE = "CREATE_INDUSTRY_FAILURE"
export const createIndustryAction = createAsyncAction(
    CREATE_INDUSTRY_REQUEST,
    CREATE_INDUSTRY_SUCCESS,
    CREATE_INDUSTRY_FAILURE
)<CREATEINDUSTRYCRED, void, void>()

const UPDATE_INDUSTRY_REQUEST = "UPDATE_INDUSTRY_REQUEST"
const UPDATE_INDUSTRY_SUCCESS = "UPDATE_INDUSTRY_SUCCESS"
const UPDATE_INDUSTRY_FAILURE = "UPDATE_INDUSTRY_FAILURE"
export const updateIndustryAction = createAsyncAction(
    UPDATE_INDUSTRY_REQUEST,
    UPDATE_INDUSTRY_SUCCESS,
    UPDATE_INDUSTRY_FAILURE
)<UPDATEINDUSTRYCRED, void, void>()


const DELETE_INDUSTRY_REQUEST = "DELETE_INDUSTRY_REQUEST"
const DELETE_INDUSTRY_SUCCESS = "DELETE_INDUSTRY_SUCCESS"
const DELETE_INDUSTRY_FAILURE = "DELETE_INDUSTRY_FAILURE"
export const deleteIndustryAction = createAsyncAction(
    DELETE_INDUSTRY_REQUEST,
    DELETE_INDUSTRY_SUCCESS,
    DELETE_INDUSTRY_FAILURE
)<string, string, void>()