import { createAsyncAction, createAction } from "typesafe-actions";
import { ShortIncentive, CREATESHORTINCENTIVECRED, UPDATESHORTINCENTIVECRED } from "../interface/shortincentiveInterface";

const SELECT_SHORTINCENTIVE = "SELECT_SHORTINCENTIVE"
export const selectShortIncentiveAction = createAction(SELECT_SHORTINCENTIVE,
    action => {
        return (shortincentive: ShortIncentive) => action(shortincentive)
    })

const GET_SHORTINCENTIVE_LIST_REQUEST = "GET_SHORTINCENTIVE_LIST_REQUEST"
const GET_SHORTINCENTIVE_LIST_SUCCESS = "GET_SHORTINCENTIVE_LIST_SUCCESS"
const GET_SHORTINCENTIVE_LIST_FAILURE = "GET_SHORTINCENTIVE_LIST_FAILURE"
export const getShortIncentiveListAction = createAsyncAction(
    GET_SHORTINCENTIVE_LIST_REQUEST,
    GET_SHORTINCENTIVE_LIST_SUCCESS,
    GET_SHORTINCENTIVE_LIST_FAILURE
)<void, ShortIncentive[], void>()

const CREATE_SHORTINCENTIVE_REQUEST = "CREATE_SHORTINCENTIVE_REQUEST"
const CREATE_SHORTINCENTIVE_SUCCESS = "CREATE_SHORTINCENTIVE_SUCCESS"
const CREATE_SHORTINCENTIVE_FAILURE = "CREATE_SHORTINCENTIVE_FAILURE"
export const createShortIncentiveAction = createAsyncAction(
    CREATE_SHORTINCENTIVE_REQUEST,
    CREATE_SHORTINCENTIVE_SUCCESS,
    CREATE_SHORTINCENTIVE_FAILURE
)<CREATESHORTINCENTIVECRED, void, void>()

const UPDATE_SHORTINCENTIVE_REQUEST = "UPDATE_SHORTINCENTIVE_REQUEST"
const UPDATE_SHORTINCENTIVE_SUCCESS = "UPDATE_SHORTINCENTIVE_SUCCESS"
const UPDATE_SHORTINCENTIVE_FAILURE = "UPDATE_SHORTINCENTIVE_FAILURE"
export const updateShortIncentiveAction = createAsyncAction(
    UPDATE_SHORTINCENTIVE_REQUEST,
    UPDATE_SHORTINCENTIVE_SUCCESS,
    UPDATE_SHORTINCENTIVE_FAILURE
)<UPDATESHORTINCENTIVECRED, void, void>()

const DELETE_SHORTINCENTIVE_REQUEST = "DELETE_SHORTINCENTIVE_REQUEST"
const DELETE_SHORTINCENTIVE_SUCCESS = "DELETE_SHORTINCENTIVE_SUCCESS"
const DELETE_SHORTINCENTIVE_FAILURE = "DELETE_SHORTINCENTIVE_FAILURE"
export const deleteShortIncentiveAction = createAsyncAction(
    DELETE_SHORTINCENTIVE_REQUEST,
    DELETE_SHORTINCENTIVE_SUCCESS,
    DELETE_SHORTINCENTIVE_FAILURE
)<string, void, void>()