import { createAsyncAction, createAction } from "typesafe-actions";
import { TargetBonus, CREATETARGETBONUSCRED, UPDATETARGETBONUSCRED } from "../interface/targetbonusInterface";

const SELECT_TARGETBONUS = "SELECT_TARGETBONUS"
export const selectTargetBonusAction = createAction(SELECT_TARGETBONUS,
    action => {
        return (targetbonus: TargetBonus) => action(targetbonus)
    })

const GET_TARGETBONUS_LIST_REQUEST = "GET_TARGETBONUS_LIST_REQUEST"
const GET_TARGETBONUS_LIST_SUCCESS = "GET_TARGETBONUS_LIST_SUCCESS"
const GET_TARGETBONUS_LIST_FAILURE = "GET_TARGETBONUS_LIST_FAILURE"
export const getTargetBonusListAction = createAsyncAction(
    GET_TARGETBONUS_LIST_REQUEST,
    GET_TARGETBONUS_LIST_SUCCESS,
    GET_TARGETBONUS_LIST_FAILURE
)<void, TargetBonus[], void>()

const CREATE_TARGETBONUS_REQUEST = "CREATE_TARGETBONUS_REQUEST"
const CREATE_TARGETBONUS_SUCCESS = "CREATE_TARGETBONUS_SUCCESS"
const CREATE_TARGETBONUS_FAILURE = "CREATE_TARGETBONUS_FAILURE"
export const createTargetBonusAction = createAsyncAction(
    CREATE_TARGETBONUS_REQUEST,
    CREATE_TARGETBONUS_SUCCESS,
    CREATE_TARGETBONUS_FAILURE
)<CREATETARGETBONUSCRED, void, void>()

const UPDATE_TARGETBONUS_REQUEST = "UPDATE_TARGETBONUS_REQUEST"
const UPDATE_TARGETBONUS_SUCCESS = "UPDATE_TARGETBONUS_SUCCESS"
const UPDATE_TARGETBONUS_FAILURE = "UPDATE_TARGETBONUS_FAILURE"
export const updateTargetBonusAction = createAsyncAction(
    UPDATE_TARGETBONUS_REQUEST,
    UPDATE_TARGETBONUS_SUCCESS,
    UPDATE_TARGETBONUS_FAILURE
)<UPDATETARGETBONUSCRED, void, void>()

const DELETE_TARGETBONUS_REQUEST = "DELETE_TARGETBONUS_REQUEST"
const DELETE_TARGETBONUS_SUCCESS = "DELETE_TARGETBONUS_SUCCESS"
const DELETE_TARGETBONUS_FAILURE = "DELETE_TARGETBONUS_FAILURE"
export const deleteTargetBonusAction = createAsyncAction(
    DELETE_TARGETBONUS_REQUEST,
    DELETE_TARGETBONUS_SUCCESS,
    DELETE_TARGETBONUS_FAILURE
)<string, void, void>()
